# Generated by Django 4.2.5 on 2023-11-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totalItems',
            field=models.IntegerField(default=0),
        ),
    ]
