# Generated by Django 4.2.5 on 2023-11-02 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freights', '0002_alter_freight_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shippingCompany', models.CharField(max_length=50)),
                ('totalCharge', models.CharField(max_length=50)),
                ('departureDate', models.CharField(max_length=50)),
                ('arrivalDate', models.CharField(max_length=50)),
                ('isFCL', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isAccepted', models.BooleanField(default=False)),
                ('freightId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freights.freight')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
